export const zones = [
    "Changhua County, Taiwan, APAC",
    "Hong Kong, APAC",
    "Tokyo, Japan, APAC",
    "Seoul, South Korea, APAC",
    "Mumbai, India, APAC",
    "Jurong West, Singapore, APAC",
    "Jakarta, Indonesia, APAC",
    "Sydney, Australia, APAC",
    "Warsaw, Poland, Europe",
    "St. Ghislain, Belgium, Europe",
    "London, England, Europe",
    "Frankfurt, Germany, Europe",
    "Eemshaven, Netherlands, Europe",
    "Tel Aviv, Israel, Middle East",
    "Montréal, Québec, North America",
    "Osasco, São Paulo, Brazil, South America",
    "Council Bluffs, Iowa, North America",
    "Moncks Corner, South Carolina, North America",
    "Ashburn, Virginia, North America",
    "The Dalles, Oregon, North America",
    "Los Angeles, California, North America",
    "Salt Lake City, Utah, North America",
    "Las Vegas, Nevada, North America"
  ]