export const zones = [
  "Ashburn, Virginia, North America",
  "Berlin, Germany, Europe",
  "Changhua County, Taiwan, APAC",
  "Columbus, Ohio, North America",
  "Council Bluffs, Iowa, North America",
  "Dallas, Texas, North America",
  "Dammam, Saudi Arabia, Middle East",
  "Delhi, India, APAC",
  "Doha, Qatar, Middle East",
  "Eemshaven, Netherlands, Europe",
  "Frankfurt, Germany, Europe",
  "Hamina, Finland, Europe",
  "Hong Kong, APAC",
  "Jakarta, Indonesia, APAC",
  "Johannesburg, South Africa",
  "Jurong West, Singapore, APAC",
  "Las Vegas, Nevada, North America",
  "London, England, Europe",
  "Los Angeles, California, North America",
  "Madrid, Spain, Europe",
  "Melbourne, Australia, APAC",
  "Milan, Italy, Europe",
  "Moncks Corner, South Carolina, North America",
  "Montréal, Québec, North America",
  "Mumbai, India, APAC",
  "Osaka, Japan, APAC",
  "Osasco, São Paulo, Brazil, South America",
  "Paris, France, Europe",
  "Salt Lake City, Utah, North America",
  "Santiago, Chile, South America",
  "Seoul, South Korea, APAC",
  "St. Ghislain, Belgium, Europe",
  "Sydney, Australia, APAC",
  "Tel Aviv, Israel, Middle East",
  "The Dalles, Oregon, North America",
  "Tokyo, Japan, APAC",
  "Toronto, Ontario, North America",
  "Turin, Italy, Europe",
  "Warsaw, Poland, Europe",
  "Zurich, Switzerland, Europe"
];